/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrkestriaAdminIndexRouteImport } from './routes/orkestria-admin.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as OrkestriaAdminTenantsRouteImport } from './routes/orkestria-admin.tenants'
import { Route as DashboardOrcamentoRouteImport } from './routes/dashboard.orcamento'
import { Route as DashboardNotasFiscaisRouteImport } from './routes/dashboard.notas-fiscais'
import { Route as DashboardIndicadoresRouteImport } from './routes/dashboard.indicadores'
import { Route as DashboardFornecedoresRouteImport } from './routes/dashboard.fornecedores'
import { Route as DashboardFluxoDeCaixaRouteImport } from './routes/dashboard.fluxo-de-caixa'
import { Route as DashboardDreRouteImport } from './routes/dashboard.dre'
import { Route as DashboardBalancoRouteImport } from './routes/dashboard.balanco'
import { Route as DashboardAnaliseRouteImport } from './routes/dashboard.analise'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminUploadRouteImport } from './routes/admin.upload'
import { Route as AdminSistemasRouteImport } from './routes/admin.sistemas'
import { Route as AdminSegmentosRouteImport } from './routes/admin.segmentos'
import { Route as AdminPlanoPadraoRouteImport } from './routes/admin.plano-padrao'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminIndicadoresRouteImport } from './routes/admin.indicadores'
import { Route as AdminEmpresasRouteImport } from './routes/admin.empresas'
import { Route as AdminDiagnosticoRouteImport } from './routes/admin.diagnostico'
import { Route as AdminComparativoRouteImport } from './routes/admin.comparativo'
import { Route as AdminEmpresasIndexRouteImport } from './routes/admin.empresas.index'
import { Route as AdminEmpresasIdDadosRouteImport } from './routes/admin.empresas.$id.dados'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrkestriaAdminIndexRoute = OrkestriaAdminIndexRouteImport.update({
  id: '/orkestria-admin/',
  path: '/orkestria-admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrkestriaAdminTenantsRoute = OrkestriaAdminTenantsRouteImport.update({
  id: '/orkestria-admin/tenants',
  path: '/orkestria-admin/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrcamentoRoute = DashboardOrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotasFiscaisRoute = DashboardNotasFiscaisRouteImport.update({
  id: '/notas-fiscais',
  path: '/notas-fiscais',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIndicadoresRoute = DashboardIndicadoresRouteImport.update({
  id: '/indicadores',
  path: '/indicadores',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFornecedoresRoute = DashboardFornecedoresRouteImport.update({
  id: '/fornecedores',
  path: '/fornecedores',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFluxoDeCaixaRoute = DashboardFluxoDeCaixaRouteImport.update({
  id: '/fluxo-de-caixa',
  path: '/fluxo-de-caixa',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDreRoute = DashboardDreRouteImport.update({
  id: '/dre',
  path: '/dre',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBalancoRoute = DashboardBalancoRouteImport.update({
  id: '/balanco',
  path: '/balanco',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnaliseRoute = DashboardAnaliseRouteImport.update({
  id: '/analise',
  path: '/analise',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUploadRoute = AdminUploadRouteImport.update({
  id: '/admin/upload',
  path: '/admin/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSistemasRoute = AdminSistemasRouteImport.update({
  id: '/admin/sistemas',
  path: '/admin/sistemas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSegmentosRoute = AdminSegmentosRouteImport.update({
  id: '/admin/segmentos',
  path: '/admin/segmentos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlanoPadraoRoute = AdminPlanoPadraoRouteImport.update({
  id: '/admin/plano-padrao',
  path: '/admin/plano-padrao',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndicadoresRoute = AdminIndicadoresRouteImport.update({
  id: '/admin/indicadores',
  path: '/admin/indicadores',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmpresasRoute = AdminEmpresasRouteImport.update({
  id: '/admin/empresas',
  path: '/admin/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDiagnosticoRoute = AdminDiagnosticoRouteImport.update({
  id: '/admin/diagnostico',
  path: '/admin/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminComparativoRoute = AdminComparativoRouteImport.update({
  id: '/admin/comparativo',
  path: '/admin/comparativo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmpresasIndexRoute = AdminEmpresasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminEmpresasRoute,
} as any)
const AdminEmpresasIdDadosRoute = AdminEmpresasIdDadosRouteImport.update({
  id: '/$id/dados',
  path: '/$id/dados',
  getParentRoute: () => AdminEmpresasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/admin/comparativo': typeof AdminComparativoRoute
  '/admin/diagnostico': typeof AdminDiagnosticoRoute
  '/admin/empresas': typeof AdminEmpresasRouteWithChildren
  '/admin/indicadores': typeof AdminIndicadoresRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/plano-padrao': typeof AdminPlanoPadraoRoute
  '/admin/segmentos': typeof AdminSegmentosRoute
  '/admin/sistemas': typeof AdminSistemasRoute
  '/admin/upload': typeof AdminUploadRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/dashboard/analise': typeof DashboardAnaliseRoute
  '/dashboard/balanco': typeof DashboardBalancoRoute
  '/dashboard/dre': typeof DashboardDreRoute
  '/dashboard/fluxo-de-caixa': typeof DashboardFluxoDeCaixaRoute
  '/dashboard/fornecedores': typeof DashboardFornecedoresRoute
  '/dashboard/indicadores': typeof DashboardIndicadoresRoute
  '/dashboard/notas-fiscais': typeof DashboardNotasFiscaisRoute
  '/dashboard/orcamento': typeof DashboardOrcamentoRoute
  '/orkestria-admin/tenants': typeof OrkestriaAdminTenantsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/orkestria-admin/': typeof OrkestriaAdminIndexRoute
  '/admin/empresas/': typeof AdminEmpresasIndexRoute
  '/admin/empresas/$id/dados': typeof AdminEmpresasIdDadosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/comparativo': typeof AdminComparativoRoute
  '/admin/diagnostico': typeof AdminDiagnosticoRoute
  '/admin/indicadores': typeof AdminIndicadoresRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/plano-padrao': typeof AdminPlanoPadraoRoute
  '/admin/segmentos': typeof AdminSegmentosRoute
  '/admin/sistemas': typeof AdminSistemasRoute
  '/admin/upload': typeof AdminUploadRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/dashboard/analise': typeof DashboardAnaliseRoute
  '/dashboard/balanco': typeof DashboardBalancoRoute
  '/dashboard/dre': typeof DashboardDreRoute
  '/dashboard/fluxo-de-caixa': typeof DashboardFluxoDeCaixaRoute
  '/dashboard/fornecedores': typeof DashboardFornecedoresRoute
  '/dashboard/indicadores': typeof DashboardIndicadoresRoute
  '/dashboard/notas-fiscais': typeof DashboardNotasFiscaisRoute
  '/dashboard/orcamento': typeof DashboardOrcamentoRoute
  '/orkestria-admin/tenants': typeof OrkestriaAdminTenantsRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/orkestria-admin': typeof OrkestriaAdminIndexRoute
  '/admin/empresas': typeof AdminEmpresasIndexRoute
  '/admin/empresas/$id/dados': typeof AdminEmpresasIdDadosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/admin/comparativo': typeof AdminComparativoRoute
  '/admin/diagnostico': typeof AdminDiagnosticoRoute
  '/admin/empresas': typeof AdminEmpresasRouteWithChildren
  '/admin/indicadores': typeof AdminIndicadoresRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/plano-padrao': typeof AdminPlanoPadraoRoute
  '/admin/segmentos': typeof AdminSegmentosRoute
  '/admin/sistemas': typeof AdminSistemasRoute
  '/admin/upload': typeof AdminUploadRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/dashboard/analise': typeof DashboardAnaliseRoute
  '/dashboard/balanco': typeof DashboardBalancoRoute
  '/dashboard/dre': typeof DashboardDreRoute
  '/dashboard/fluxo-de-caixa': typeof DashboardFluxoDeCaixaRoute
  '/dashboard/fornecedores': typeof DashboardFornecedoresRoute
  '/dashboard/indicadores': typeof DashboardIndicadoresRoute
  '/dashboard/notas-fiscais': typeof DashboardNotasFiscaisRoute
  '/dashboard/orcamento': typeof DashboardOrcamentoRoute
  '/orkestria-admin/tenants': typeof OrkestriaAdminTenantsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/orkestria-admin/': typeof OrkestriaAdminIndexRoute
  '/admin/empresas/': typeof AdminEmpresasIndexRoute
  '/admin/empresas/$id/dados': typeof AdminEmpresasIdDadosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/admin/comparativo'
    | '/admin/diagnostico'
    | '/admin/empresas'
    | '/admin/indicadores'
    | '/admin/logs'
    | '/admin/plano-padrao'
    | '/admin/segmentos'
    | '/admin/sistemas'
    | '/admin/upload'
    | '/admin/usuarios'
    | '/dashboard/analise'
    | '/dashboard/balanco'
    | '/dashboard/dre'
    | '/dashboard/fluxo-de-caixa'
    | '/dashboard/fornecedores'
    | '/dashboard/indicadores'
    | '/dashboard/notas-fiscais'
    | '/dashboard/orcamento'
    | '/orkestria-admin/tenants'
    | '/admin/'
    | '/dashboard/'
    | '/orkestria-admin/'
    | '/admin/empresas/'
    | '/admin/empresas/$id/dados'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/comparativo'
    | '/admin/diagnostico'
    | '/admin/indicadores'
    | '/admin/logs'
    | '/admin/plano-padrao'
    | '/admin/segmentos'
    | '/admin/sistemas'
    | '/admin/upload'
    | '/admin/usuarios'
    | '/dashboard/analise'
    | '/dashboard/balanco'
    | '/dashboard/dre'
    | '/dashboard/fluxo-de-caixa'
    | '/dashboard/fornecedores'
    | '/dashboard/indicadores'
    | '/dashboard/notas-fiscais'
    | '/dashboard/orcamento'
    | '/orkestria-admin/tenants'
    | '/admin'
    | '/dashboard'
    | '/orkestria-admin'
    | '/admin/empresas'
    | '/admin/empresas/$id/dados'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/admin/comparativo'
    | '/admin/diagnostico'
    | '/admin/empresas'
    | '/admin/indicadores'
    | '/admin/logs'
    | '/admin/plano-padrao'
    | '/admin/segmentos'
    | '/admin/sistemas'
    | '/admin/upload'
    | '/admin/usuarios'
    | '/dashboard/analise'
    | '/dashboard/balanco'
    | '/dashboard/dre'
    | '/dashboard/fluxo-de-caixa'
    | '/dashboard/fornecedores'
    | '/dashboard/indicadores'
    | '/dashboard/notas-fiscais'
    | '/dashboard/orcamento'
    | '/orkestria-admin/tenants'
    | '/admin/'
    | '/dashboard/'
    | '/orkestria-admin/'
    | '/admin/empresas/'
    | '/admin/empresas/$id/dados'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AdminComparativoRoute: typeof AdminComparativoRoute
  AdminDiagnosticoRoute: typeof AdminDiagnosticoRoute
  AdminEmpresasRoute: typeof AdminEmpresasRouteWithChildren
  AdminIndicadoresRoute: typeof AdminIndicadoresRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminPlanoPadraoRoute: typeof AdminPlanoPadraoRoute
  AdminSegmentosRoute: typeof AdminSegmentosRoute
  AdminSistemasRoute: typeof AdminSistemasRoute
  AdminUploadRoute: typeof AdminUploadRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  OrkestriaAdminTenantsRoute: typeof OrkestriaAdminTenantsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  OrkestriaAdminIndexRoute: typeof OrkestriaAdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orkestria-admin/': {
      id: '/orkestria-admin/'
      path: '/orkestria-admin'
      fullPath: '/orkestria-admin/'
      preLoaderRoute: typeof OrkestriaAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orkestria-admin/tenants': {
      id: '/orkestria-admin/tenants'
      path: '/orkestria-admin/tenants'
      fullPath: '/orkestria-admin/tenants'
      preLoaderRoute: typeof OrkestriaAdminTenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/orcamento': {
      id: '/dashboard/orcamento'
      path: '/orcamento'
      fullPath: '/dashboard/orcamento'
      preLoaderRoute: typeof DashboardOrcamentoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notas-fiscais': {
      id: '/dashboard/notas-fiscais'
      path: '/notas-fiscais'
      fullPath: '/dashboard/notas-fiscais'
      preLoaderRoute: typeof DashboardNotasFiscaisRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/indicadores': {
      id: '/dashboard/indicadores'
      path: '/indicadores'
      fullPath: '/dashboard/indicadores'
      preLoaderRoute: typeof DashboardIndicadoresRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/fornecedores': {
      id: '/dashboard/fornecedores'
      path: '/fornecedores'
      fullPath: '/dashboard/fornecedores'
      preLoaderRoute: typeof DashboardFornecedoresRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/fluxo-de-caixa': {
      id: '/dashboard/fluxo-de-caixa'
      path: '/fluxo-de-caixa'
      fullPath: '/dashboard/fluxo-de-caixa'
      preLoaderRoute: typeof DashboardFluxoDeCaixaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/dre': {
      id: '/dashboard/dre'
      path: '/dre'
      fullPath: '/dashboard/dre'
      preLoaderRoute: typeof DashboardDreRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/balanco': {
      id: '/dashboard/balanco'
      path: '/balanco'
      fullPath: '/dashboard/balanco'
      preLoaderRoute: typeof DashboardBalancoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analise': {
      id: '/dashboard/analise'
      path: '/analise'
      fullPath: '/dashboard/analise'
      preLoaderRoute: typeof DashboardAnaliseRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/upload': {
      id: '/admin/upload'
      path: '/admin/upload'
      fullPath: '/admin/upload'
      preLoaderRoute: typeof AdminUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sistemas': {
      id: '/admin/sistemas'
      path: '/admin/sistemas'
      fullPath: '/admin/sistemas'
      preLoaderRoute: typeof AdminSistemasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/segmentos': {
      id: '/admin/segmentos'
      path: '/admin/segmentos'
      fullPath: '/admin/segmentos'
      preLoaderRoute: typeof AdminSegmentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/plano-padrao': {
      id: '/admin/plano-padrao'
      path: '/admin/plano-padrao'
      fullPath: '/admin/plano-padrao'
      preLoaderRoute: typeof AdminPlanoPadraoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/indicadores': {
      id: '/admin/indicadores'
      path: '/admin/indicadores'
      fullPath: '/admin/indicadores'
      preLoaderRoute: typeof AdminIndicadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/empresas': {
      id: '/admin/empresas'
      path: '/admin/empresas'
      fullPath: '/admin/empresas'
      preLoaderRoute: typeof AdminEmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/diagnostico': {
      id: '/admin/diagnostico'
      path: '/admin/diagnostico'
      fullPath: '/admin/diagnostico'
      preLoaderRoute: typeof AdminDiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/comparativo': {
      id: '/admin/comparativo'
      path: '/admin/comparativo'
      fullPath: '/admin/comparativo'
      preLoaderRoute: typeof AdminComparativoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/empresas/': {
      id: '/admin/empresas/'
      path: '/'
      fullPath: '/admin/empresas/'
      preLoaderRoute: typeof AdminEmpresasIndexRouteImport
      parentRoute: typeof AdminEmpresasRoute
    }
    '/admin/empresas/$id/dados': {
      id: '/admin/empresas/$id/dados'
      path: '/$id/dados'
      fullPath: '/admin/empresas/$id/dados'
      preLoaderRoute: typeof AdminEmpresasIdDadosRouteImport
      parentRoute: typeof AdminEmpresasRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnaliseRoute: typeof DashboardAnaliseRoute
  DashboardBalancoRoute: typeof DashboardBalancoRoute
  DashboardDreRoute: typeof DashboardDreRoute
  DashboardFluxoDeCaixaRoute: typeof DashboardFluxoDeCaixaRoute
  DashboardFornecedoresRoute: typeof DashboardFornecedoresRoute
  DashboardIndicadoresRoute: typeof DashboardIndicadoresRoute
  DashboardNotasFiscaisRoute: typeof DashboardNotasFiscaisRoute
  DashboardOrcamentoRoute: typeof DashboardOrcamentoRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnaliseRoute: DashboardAnaliseRoute,
  DashboardBalancoRoute: DashboardBalancoRoute,
  DashboardDreRoute: DashboardDreRoute,
  DashboardFluxoDeCaixaRoute: DashboardFluxoDeCaixaRoute,
  DashboardFornecedoresRoute: DashboardFornecedoresRoute,
  DashboardIndicadoresRoute: DashboardIndicadoresRoute,
  DashboardNotasFiscaisRoute: DashboardNotasFiscaisRoute,
  DashboardOrcamentoRoute: DashboardOrcamentoRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface AdminEmpresasRouteChildren {
  AdminEmpresasIndexRoute: typeof AdminEmpresasIndexRoute
  AdminEmpresasIdDadosRoute: typeof AdminEmpresasIdDadosRoute
}

const AdminEmpresasRouteChildren: AdminEmpresasRouteChildren = {
  AdminEmpresasIndexRoute: AdminEmpresasIndexRoute,
  AdminEmpresasIdDadosRoute: AdminEmpresasIdDadosRoute,
}

const AdminEmpresasRouteWithChildren = AdminEmpresasRoute._addFileChildren(
  AdminEmpresasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AdminComparativoRoute: AdminComparativoRoute,
  AdminDiagnosticoRoute: AdminDiagnosticoRoute,
  AdminEmpresasRoute: AdminEmpresasRouteWithChildren,
  AdminIndicadoresRoute: AdminIndicadoresRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminPlanoPadraoRoute: AdminPlanoPadraoRoute,
  AdminSegmentosRoute: AdminSegmentosRoute,
  AdminSistemasRoute: AdminSistemasRoute,
  AdminUploadRoute: AdminUploadRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  OrkestriaAdminTenantsRoute: OrkestriaAdminTenantsRoute,
  AdminIndexRoute: AdminIndexRoute,
  OrkestriaAdminIndexRoute: OrkestriaAdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
