ALTER FUNCTION public.plano_padrao_resumo(uuid) SECURITY INVOKER;
ALTER FUNCTION public.dfc_cobertura(uuid, uuid) SECURITY INVOKER;
REVOKE ALL ON FUNCTION public.plano_padrao_resumo(uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public.dfc_cobertura(uuid, uuid) FROM PUBLIC, anon;
REVOKE ALL ON FUNCTION public._garantir_sinteticas_interno(uuid, uuid, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.garantir_sinteticas_faltantes(uuid, uuid, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.plano_padrao_resumo(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.dfc_cobertura(uuid, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public._garantir_sinteticas_interno(uuid, uuid, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.garantir_sinteticas_faltantes(uuid, uuid, text) TO authenticated, service_role;
NOTIFY pgrst, 'reload schema';